from typing import Any, Dict, List


POLICY_CANDIDATES: List[Dict[str, Any]] = [
    {
        "policy_id": "seoul_brp_loan",
        "policy_name": "민간건물 에너지효율화사업 BRP 융자",
        "category": "융자",
        "benefit_type": "공사비 융자",
        "summary": "노후 민간 건축물의 에너지 성능개선 공사비를 저리 융자로 지원하는 사업입니다.",
        "target": "서울 소재 민간건축물 중 사용승인 후 15년 이상 경과한 건물",
        "support_items": ["창호 교체", "단열 보강", "LED 조명 교체", "BEMS/자동제어", "고효율 냉난방기", "히트펌프", "태양광/신재생에너지"],
        "required_data": ["use_apr_day", "public_private_type", "improvement_interests"],
        "official_url": "https://housing.seoul.go.kr",
        "caution": "실제 신청 가능 여부와 한도, 금리는 최신 공고문 확인이 필요합니다.",
    },
    {
        "policy_id": "seoul_saebit_housing",
        "policy_name": "새빛주택 보조금",
        "category": "보조금",
        "benefit_type": "주택 에너지 개선 보조금",
        "summary": "노후 주택의 창호, 조명, 차열도장 개선 비용 일부를 지원하는 사업입니다.",
        "target": "15년 이상 경과한 주택 중 공시가격 등 세부 조건을 충족하는 주택",
        "support_items": ["창호 교체", "LED 조명 교체", "단열 보강"],
        "required_data": ["use_apr_day", "housing_type", "official_price_band", "owner_or_tenant"],
        "official_url": "https://housing.seoul.go.kr",
        "caution": "공시가격, 소유자/세입자 여부 등 세부 조건 확인이 필요합니다.",
    },
    {
        "policy_id": "public_green_remodeling",
        "policy_name": "공공건축물 그린리모델링",
        "category": "공공건축물 보조/사업 지원",
        "benefit_type": "공공건축물 성능개선 사업",
        "summary": "공공건축물의 창호, 단열, 고효율 냉난방기 등 성능개선 공사와 연결되는 사업입니다.",
        "target": "사용승인 후 10년 이상 경과한 공공건축물",
        "support_items": ["창호 교체", "단열 보강", "고효율 냉난방기", "BEMS/자동제어"],
        "required_data": ["use_apr_day", "public_private_type", "facility_type"],
        "official_url": "https://www.greenremodeling.or.kr",
        "caution": "대상 시설과 사업 방식은 연도별 공고 및 담당 기관 확인이 필요합니다.",
    },
    {
        "policy_id": "high_efficiency_window_simple_install",
        "policy_name": "고효율 창호 간편시공",
        "category": "무료 시공 지원",
        "benefit_type": "단열덧유리·기밀방풍재 무료 설치",
        "summary": "취약계층 주택에 단열덧유리와 기밀방풍재 등을 무료 설치하는 지원입니다.",
        "target": "서울시 거주 차상위 이하 취약계층 주택",
        "support_items": ["창호 교체", "단열 보강"],
        "required_data": ["housing_type", "vulnerable_group", "recent_home_repair_support", "owner_or_tenant"],
        "official_url": "https://housing.seoul.go.kr",
        "caution": "취약계층 여부는 민감 정보이므로 응답하지 않아도 되며, 실제 대상 여부는 별도 확인이 필요합니다.",
    },
    {
        "policy_id": "eco_mileage",
        "policy_name": "에코마일리지",
        "category": "인센티브/마일리지",
        "benefit_type": "에너지 절감 인센티브",
        "summary": "에너지 절감 실적에 따라 인센티브를 받을 수 있는 참여형 제도입니다.",
        "target": "서울시 거주 시민 또는 서울시 내 법인, 개인사업자, 단체",
        "support_items": ["에너지 절감 실천", "사용량 모니터링"],
        "required_data": ["participant_type", "energy_saving_record"],
        "official_url": "https://ecomileage.seoul.go.kr",
        "caution": "인센티브는 실제 절감 실적과 제도 운영 기준에 따라 달라질 수 있습니다.",
    },
    {
        "policy_id": "zeb_ai_optimization_consulting",
        "policy_name": "ZEB AI 최적화 컨설팅",
        "category": "컨설팅 연계",
        "benefit_type": "에너지 최적화 컨설팅",
        "summary": "에너지 사용량이 높거나 자동제어/BEMS가 없는 건물의 운영 최적화 컨설팅 후보입니다.",
        "target": "에너지 사용량이 높거나 자동제어, 고효율 설비 개선 검토가 필요한 건물",
        "support_items": ["BEMS/자동제어", "고효율 냉난방기", "히트펌프", "운영 최적화"],
        "required_data": ["energy_overuse", "bems", "improvement_interests"],
        "official_url": None,
        "caution": "현재는 상담 연결 후보이며, 실제 지원사업 선정이나 보조금을 의미하지 않습니다.",
    },
    {
        "policy_id": "renewable_energy_consulting",
        "policy_name": "에너지 컨설팅 및 신재생에너지 컨설팅 연계",
        "category": "컨설팅/시공 연계",
        "benefit_type": "신재생·고효율 설비 상담 연결",
        "summary": "태양광, 신재생에너지, 고효율 설비, 자동제어 개선 상담과 연결할 수 있는 후보입니다.",
        "target": "전기 사용량이 높거나 운영시간이 길고 신재생·설비 개선 검토가 필요한 건물",
        "support_items": ["태양광/신재생에너지", "고효율 냉난방기", "BEMS/자동제어", "LED 조명 교체"],
        "required_data": ["electric_overuse", "solar_generation", "major_electric_equipment", "improvement_interests"],
        "official_url": None,
        "caution": "현재는 상담 연결 후보이며, 실제 업체명이나 전화번호는 제공하지 않습니다.",
    },
]


EXCLUDED_RECOMMENDATION_POLICY_NAMES: List[str] = [
    "건물 에너지 신고·등급제",
    "건물 온실가스 총량제",
]


CONTRACTOR_CATEGORIES: List[Dict[str, str]] = [
    {"category": "조명/전기 설비", "cta_label": "조명·전기 설비 상담 연결 준비 중"},
    {"category": "냉난방기 점검", "cta_label": "냉난방 설비 상담 연결 준비 중"},
    {"category": "보일러/난방 설비", "cta_label": "난방 설비 상담 연결 준비 중"},
    {"category": "단열/창호", "cta_label": "단열·창호 상담 연결 준비 중"},
    {"category": "BEMS/자동제어", "cta_label": "자동제어 상담 연결 준비 중"},
    {"category": "태양광/신재생에너지", "cta_label": "신재생에너지 상담 연결 준비 중"},
]
